### PR TITLE
Added packager port

### PR DESCRIPTION
**Pull request by sbmueller**
Recipes for packager port (https://github.com/gnuradio/pybombs/pull/289)

### CODE REVIEW

**Comment by mbr0wn** [comment]
...Waiting for @sdh11 's signoff on the actual package manager on pybombs. In the meantime, can you squash these please?

**Comment by sbmueller** [comment]
@mbr0wn I think this is ready to be merged, isn't it? Otherwise, please let me know if there is anything more to be done here.

**Comment by sdh11** [comment]
Sorry, I forgot to update this. It isn't ready for merging yet. On a clean system, there are several packages that macports fails to install due to conflicts. I can't remember them off hand, but the issue is resolved if I first install gnuradio through macports and then try running pybombs. 

Can you make sure that the package names in the recipes match what is installed through the gnuradio port? https://www.macports.org/ports.php?by=variant&substr=grc

**Comment by sdh11** [comment]
I do know that the qt package should be qt4-mac and not qt4-x11. The latest version of qt4-x11 listed on the macports site is 4.4.3.

**Comment by sbmueller** [comment]
Ahh I see. I will have a look 👍

**Comment by sbmueller** [comment]
@sdh11 I have revisited the recipes and I think everything should be fine now. I uninstalled gnuradio within ports and did a `port uninstall leaves` to get rid of the dependencies. When running pybombs now, I get as far as building gnuradio from source.

**Comment by sbmueller** [comment]
@sdh11 With the changes in https://github.com/gnuradio/gnuradio/pull/814 even GNU Radio should build  without issues now. Remember to set the 
```
config_opt: ' -DPYTHON_LIBRARIES=/opt/local/lib/libpython2.7.dylib -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7 '
```
for UHD and GNU Radio in pybombs config :)

**Pull request closed without merging**
