### PR TITLE
gr-bladeRF: add gr-osmosdr dependency

### PR DESCRIPTION
**Pull request by rthomp10**
Fixes the gr-osmosdr prerequisite for gr-bladeRF.

### CODE REVIEW

**Comment by willcode** [comment]
Could you check whether the dependency is really on osmosdr, and not gr-osmosdr? This package is an alternative to using BladeRF through gr-osmosdr, so it's surprising it would require it.

**Comment by willcode** [comment]
Since you're the author of gr-bladeRF (I think?) is there a way to make gr-bladeRF dependend only on osmosdr? I think it should only need the types (e.g., range) from there, and can do everything else without gr-osmosdr.

**Comment by rthomp10** [comment]
@rghilduta and I are the current authors. As of this build, gr-bladeRF is dependent on gr-osmosdr. Currently looking into relying on just osmo-sdr.

**Comment by willcode** [comment]
We can merge now or wait until you look into it. Your choice.

**Comment by rthomp10** [comment]
Let's go ahead and merge for now.

**Pull request merged**
